image: golang:latest

stages:
  # - test
  - build
  - upload
  # - deploy

Build:
  stage: build
  script:
    - make build-all
  artifacts:
    paths:
      - bin
      - CURRENT_VERSION

Upload:
  stage: upload
  image:
    name: minio/mc
    entrypoint: ['']
  needs:
    - job: Build
      artifacts: true
  before_script:
    - mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
  script:
    - mc cp bin/* minio/$MINIO_BUCKET/$TAG_COMMIT/
    - mc cp bin/* minio/$MINIO_BUCKET/latest/
    - mc cp CURRENT_VERSION minio/$MINIO_BUCKET/

# Deploy:
#   stage: deploy
#   release:
#     tag_name: 'v1.$CI_PIPELINE_IID'
#     description: 'v1.$CI_PIPELINE_IID'
#     ref: '$CI_COMMIT_SHA'