name: test-build-and-deploy
run-name: Test, Build, and deploy binary
on: [push]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test CopyCat
        run: go test -v ./...
      - name: Build CopyCat
        run: make build-all
  Deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build CopyCat
        run: make build-all
