name: test-build-and-deploy
run-name: Test, Build, and deploy binary
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test CopyCat
        run: go test -v ./...
        env:
          DUMMY_HOST: ${{ secrets.TESTING_HOST }}
          DUMMY_KEY: ${{ secrets.TESTING_KEY }}
          DUMMY_SECRET: ${{ secrets.TESTING_SECRET }}
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build CopyCat
        run: make build-all
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: copycat-release
          path: |
            bin
            CURRENT_VERSION
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download copycat build
        uses: actions/download-artifact@v3
        with:
          name: copycat-release
      - name: Deploy to S3
        run: |
          old_version=$(cat CURRENT_VERSION)
          aws s3 --recursive mv ${{ secrets.AWS_ROOT_BUCKET }}/latest/ ${{ secrets.AWS_ROOT_BUCKET }}/${old_version}/
          aws s3 mv ${{ secrets.AWS_ROOT_BUCKET }}/CURRENT_VERSION ${{ secrets.AWS_ROOT_BUCKET }}/${old_version}/
          aws s3 sync ./bin ${{ secrets.AWS_ROOT_BUCKET }}/latest/
          aws s3 cp CURRENT_VERSION ${{ secrets.AWS_ROOT_BUCKET }}/
          aws s3api put-object-tagging --bucket ${{ secrets.AWS_BUCKET_NAME }} --key ${{ secrets.AWS_ROOT_PATH }}/CURRENT_VERSION --tagging ${{ secrets.AWS_OBJECT_TAGGING }}
          aws s3api list-objects --bucket ${{ secrets.AWS_BUCKET_NAME }} --query 'Contents[].{Key:Key}' --prefix ${{ secrets.AWS_ROOT_PATH }}/latest --output text | xargs -n 1 aws s3api put-object-tagging  --bucket ${{ secrets.AWS_BUCKET_NAME }} --tagging ${{ secrets.AWS_OBJECT_TAGGING }} --key
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          VERSION_LOG: ${{ DEPLOY_VERS_LOG }}
          VERSION_HOST: ${{ DEPLOY_VERS_HOST }}
