name: test-build-and-deploy
run-name: Test, Build, and deploy binary
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test CopyCat
        run: go test -v ./...
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build CopyCat
        run: make build-all
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: copycat-release
          path: |
            bin
            CURRENT_VERSION
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: copycat-release
      - name: Deploy to S3
        run: |
          old_version=$(cat CURRENT_VERSION)
          aws s3 --recursive mv ${{ secrets.AWS_ROOT_BUCKET }}/latest/ ${{ secrets.AWS_ROOT_BUCKET }}/${old_version}/
          aws s3 sync ./bin ${{ secrets.AWS_ROOT_BUCKET }}/latest/
          aws s3 sync CURRENT_VERSION ${{ secrets.AWS_ROOT_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
