name: Create release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: master
          check-name: "Build binaries"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download copycat build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yml
          workflow_conclusion: success

          name: copycat-release
      - name: Create release (latest)
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            LICENSE.md
            ./bin/*
      - name: Create release (version specific)
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          prerelease: false
          title: "Development Build"
          files: |
            LICENSE.md
            ./bin/*
